name: Build and publish to Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './algonim/package-lock.json'

    - name: Install dependencies
      run: |
        cd algonim
        npm ci --ignore-scripts

    - name: Compatibile licenses only
      run: |
        cd algonim
        # license-checker isn't a dependency, so npx will ask to download it => --yes
        ./license-checker.sh --yes

    - name: Build & Test
      run: |
        cd algonim
        npm run build
        npm run test

    - name: Generate docs with TypeDoc
      run: |
        cd algonim
        npx typedoc

    - name: Compose artifact
      run: |
        mkdir page
        cp -r algonim/dist ./page/
        cp -r algonim/docs ./page/
        cp ./algonim/index.html ./page/index.html
        cp ./algonim/script.js ./page/script.js

    - name: Upload artifact
      if: matrix.node-version == '22.x' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./page

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy artifact to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
